import { generateQuestionFromOriginalEssay } from "./question";
import { OriginalEssay, ParagraphSubNodeType } from "../types/essay";

test("can generate one character question", () => {
  const originalEssay: OriginalEssay = {
    name: "出師表",
    paragraphs: [
      {
        textSegments: [
          "先帝創業未半",
          "而中道崩殂",
          "今天下三分",
          "益州疲弊",
          "此誠危急存亡之秋也",
          "然侍衞之臣",
          "不懈於內；忠志之士",
          "忘身於外者",
          "蓋追先帝之殊遇",
          "欲報之於陛下也",
        ],
        subNodes: [
          { type: ParagraphSubNodeType.Text, content: "先帝創業未半" },
          { type: ParagraphSubNodeType.Punctuation, content: "，" },
          { type: ParagraphSubNodeType.Text, content: "而中道崩殂" },
          { type: ParagraphSubNodeType.Punctuation, content: "。" },
          { type: ParagraphSubNodeType.Text, content: "今天下三分" },
          { type: ParagraphSubNodeType.Punctuation, content: "，" },
          { type: ParagraphSubNodeType.Text, content: "益州疲弊" },
          { type: ParagraphSubNodeType.Punctuation, content: "，" },
          { type: ParagraphSubNodeType.Text, content: "此誠危急存亡之秋也" },
          { type: ParagraphSubNodeType.Punctuation, content: "！" },
          { type: ParagraphSubNodeType.Text, content: "然侍衞之臣" },
          { type: ParagraphSubNodeType.Punctuation, content: "，" },
          { type: ParagraphSubNodeType.Text, content: "不懈於內；忠志之士" },
          { type: ParagraphSubNodeType.Punctuation, content: "，" },
          { type: ParagraphSubNodeType.Text, content: "忘身於外者" },
          { type: ParagraphSubNodeType.Punctuation, content: "，" },
          { type: ParagraphSubNodeType.Text, content: "蓋追先帝之殊遇" },
          { type: ParagraphSubNodeType.Punctuation, content: "，" },
          { type: ParagraphSubNodeType.Text, content: "欲報之於陛下也" },
          { type: ParagraphSubNodeType.Punctuation, content: "。" },
        ],
      },
      {
        textSegments: [
          "誠宜開張聖聽",
          "以光先帝遺德",
          "恢弘志士之氣；不宜妄自菲薄",
          "引喻失義",
          "以塞忠諫之路也",
        ],
        subNodes: [
          { type: ParagraphSubNodeType.Text, content: "誠宜開張聖聽" },
          { type: ParagraphSubNodeType.Punctuation, content: "，" },
          { type: ParagraphSubNodeType.Text, content: "以光先帝遺德" },
          { type: ParagraphSubNodeType.Punctuation, content: "，" },
          { type: ParagraphSubNodeType.Text, content: "恢弘志士之氣；不宜妄自菲薄" },
          { type: ParagraphSubNodeType.Punctuation, content: "，" },
          { type: ParagraphSubNodeType.Text, content: "引喻失義" },
          { type: ParagraphSubNodeType.Punctuation, content: "，" },
          { type: ParagraphSubNodeType.Text, content: "以塞忠諫之路也" },
          { type: ParagraphSubNodeType.Punctuation, content: "。" },
        ],
      },
      {
        textSegments: [
          "宮中、府中",
          "俱為一體",
          "陟罰臧否",
          "不宜異同",
          "若有作姦、犯科",
          "及為忠善者",
          "宜付有司",
          "論其刑賞",
          "以昭陛下平明之治",
          "不宜偏私",
          "使內外異法也",
        ],
        subNodes: [
          { type: ParagraphSubNodeType.Text, content: "宮中、府中" },
          { type: ParagraphSubNodeType.Punctuation, content: "，" },
          { type: ParagraphSubNodeType.Text, content: "俱為一體" },
          { type: ParagraphSubNodeType.Punctuation, content: "，" },
          { type: ParagraphSubNodeType.Text, content: "陟罰臧否" },
          { type: ParagraphSubNodeType.Punctuation, content: "，" },
          { type: ParagraphSubNodeType.Text, content: "不宜異同" },
          { type: ParagraphSubNodeType.Punctuation, content: "。" },
          { type: ParagraphSubNodeType.Text, content: "若有作姦、犯科" },
          { type: ParagraphSubNodeType.Punctuation, content: "，" },
          { type: ParagraphSubNodeType.Text, content: "及為忠善者" },
          { type: ParagraphSubNodeType.Punctuation, content: "，" },
          { type: ParagraphSubNodeType.Text, content: "宜付有司" },
          { type: ParagraphSubNodeType.Punctuation, content: "，" },
          { type: ParagraphSubNodeType.Text, content: "論其刑賞" },
          { type: ParagraphSubNodeType.Punctuation, content: "，" },
          { type: ParagraphSubNodeType.Text, content: "以昭陛下平明之治" },
          { type: ParagraphSubNodeType.Punctuation, content: "，" },
          { type: ParagraphSubNodeType.Text, content: "不宜偏私" },
          { type: ParagraphSubNodeType.Punctuation, content: "，" },
          { type: ParagraphSubNodeType.Text, content: "使內外異法也" },
          { type: ParagraphSubNodeType.Punctuation, content: "。" },
        ],
      },
      {
        textSegments: [
          "侍中、侍郎郭攸之、費禕、董允等",
          "此皆良實",
          "志慮忠純",
          "是以先帝簡拔以遺陛下",
          "愚以為宮中之事",
          "事無大小",
          "悉以咨之",
          "然後施行",
          "必能裨補闕漏",
          "有所廣益",
          "將軍向寵",
          "性行淑均",
          "曉暢軍事",
          "試用於昔日",
          "先帝稱之曰「能」",
          "是以眾議舉寵為督",
          "愚以為營中之事",
          "悉以咨之",
          "必能使行陣和睦",
          "優劣得所",
        ],
        subNodes: [
          { type: ParagraphSubNodeType.Text, content: "侍中、侍郎郭攸之、費禕、董允等" },
          { type: ParagraphSubNodeType.Punctuation, content: "，" },
          { type: ParagraphSubNodeType.Text, content: "此皆良實" },
          { type: ParagraphSubNodeType.Punctuation, content: "，" },
          { type: ParagraphSubNodeType.Text, content: "志慮忠純" },
          { type: ParagraphSubNodeType.Punctuation, content: "，" },
          { type: ParagraphSubNodeType.Text, content: "是以先帝簡拔以遺陛下" },
          { type: ParagraphSubNodeType.Punctuation, content: "。" },
          { type: ParagraphSubNodeType.Text, content: "愚以為宮中之事" },
          { type: ParagraphSubNodeType.Punctuation, content: "，" },
          { type: ParagraphSubNodeType.Text, content: "事無大小" },
          { type: ParagraphSubNodeType.Punctuation, content: "，" },
          { type: ParagraphSubNodeType.Text, content: "悉以咨之" },
          { type: ParagraphSubNodeType.Punctuation, content: "，" },
          { type: ParagraphSubNodeType.Text, content: "然後施行" },
          { type: ParagraphSubNodeType.Punctuation, content: "，" },
          { type: ParagraphSubNodeType.Text, content: "必能裨補闕漏" },
          { type: ParagraphSubNodeType.Punctuation, content: "，" },
          { type: ParagraphSubNodeType.Text, content: "有所廣益" },
          { type: ParagraphSubNodeType.Punctuation, content: "。" },
          { type: ParagraphSubNodeType.Text, content: "將軍向寵" },
          { type: ParagraphSubNodeType.Punctuation, content: "，" },
          { type: ParagraphSubNodeType.Text, content: "性行淑均" },
          { type: ParagraphSubNodeType.Punctuation, content: "，" },
          { type: ParagraphSubNodeType.Text, content: "曉暢軍事" },
          { type: ParagraphSubNodeType.Punctuation, content: "，" },
          { type: ParagraphSubNodeType.Text, content: "試用於昔日" },
          { type: ParagraphSubNodeType.Punctuation, content: "，" },
          { type: ParagraphSubNodeType.Text, content: "先帝稱之曰「能」" },
          { type: ParagraphSubNodeType.Punctuation, content: "，" },
          { type: ParagraphSubNodeType.Text, content: "是以眾議舉寵為督" },
          { type: ParagraphSubNodeType.Punctuation, content: "。" },
          { type: ParagraphSubNodeType.Text, content: "愚以為營中之事" },
          { type: ParagraphSubNodeType.Punctuation, content: "，" },
          { type: ParagraphSubNodeType.Text, content: "悉以咨之" },
          { type: ParagraphSubNodeType.Punctuation, content: "，" },
          { type: ParagraphSubNodeType.Text, content: "必能使行陣和睦" },
          { type: ParagraphSubNodeType.Punctuation, content: "，" },
          { type: ParagraphSubNodeType.Text, content: "優劣得所" },
          { type: ParagraphSubNodeType.Punctuation, content: "。" },
        ],
      },
      {
        textSegments: [
          "親賢臣",
          "遠小人",
          "此先漢所以興隆也；親小人",
          "遠賢臣",
          "此後漢所以傾頹也",
          "先帝在時",
          "每與臣論此事",
          "未嘗不歎息痛恨於桓、靈也",
          "侍中、尚書、長史、參軍",
          "此悉貞良死節之臣",
          "願陛下親之信之",
          "則漢室之隆",
          "可計日而待也",
        ],
        subNodes: [
          { type: ParagraphSubNodeType.Text, content: "親賢臣" },
          { type: ParagraphSubNodeType.Punctuation, content: "，" },
          { type: ParagraphSubNodeType.Text, content: "遠小人" },
          { type: ParagraphSubNodeType.Punctuation, content: "，" },
          { type: ParagraphSubNodeType.Text, content: "此先漢所以興隆也；親小人" },
          { type: ParagraphSubNodeType.Punctuation, content: "，" },
          { type: ParagraphSubNodeType.Text, content: "遠賢臣" },
          { type: ParagraphSubNodeType.Punctuation, content: "，" },
          { type: ParagraphSubNodeType.Text, content: "此後漢所以傾頹也" },
          { type: ParagraphSubNodeType.Punctuation, content: "。" },
          { type: ParagraphSubNodeType.Text, content: "先帝在時" },
          { type: ParagraphSubNodeType.Punctuation, content: "，" },
          { type: ParagraphSubNodeType.Text, content: "每與臣論此事" },
          { type: ParagraphSubNodeType.Punctuation, content: "，" },
          { type: ParagraphSubNodeType.Text, content: "未嘗不歎息痛恨於桓、靈也" },
          { type: ParagraphSubNodeType.Punctuation, content: "！" },
          { type: ParagraphSubNodeType.Text, content: "侍中、尚書、長史、參軍" },
          { type: ParagraphSubNodeType.Punctuation, content: "，" },
          { type: ParagraphSubNodeType.Text, content: "此悉貞良死節之臣" },
          { type: ParagraphSubNodeType.Punctuation, content: "，" },
          { type: ParagraphSubNodeType.Text, content: "願陛下親之信之" },
          { type: ParagraphSubNodeType.Punctuation, content: "，" },
          { type: ParagraphSubNodeType.Text, content: "則漢室之隆" },
          { type: ParagraphSubNodeType.Punctuation, content: "，" },
          { type: ParagraphSubNodeType.Text, content: "可計日而待也" },
          { type: ParagraphSubNodeType.Punctuation, content: "。" },
        ],
      },
      {
        textSegments: [
          "臣本布衣",
          "躬耕於南陽",
          "苟全性命於亂世",
          "不求聞達於諸侯",
          "先帝不以臣卑鄙",
          "猥自枉屈",
          "三顧臣於草廬之中",
          "諮臣以當世之事；由是感激",
          "遂許先帝以驅馳",
          "後值傾覆",
          "受任於敗軍之際",
          "奉命於危難之間",
          "爾來二十有一年矣",
          "先帝知臣謹慎",
          "故臨崩寄臣以大事也",
          "受命以來",
          "夙夜憂歎",
          "恐託付不效",
          "以傷先帝之明",
          "故五月渡瀘",
          "深入不毛",
          "今南方已定",
          "兵甲已足",
          "當獎率三軍",
          "北定中原",
          "庶竭駑鈍",
          "攘除姦凶",
          "興復漢室",
          "還於舊都",
          "此臣所以報先帝而忠陛下之職分也",
          "至於斟酌損益",
          "進盡忠言",
          "則攸之、禕、允之任也",
        ],
        subNodes: [
          { type: ParagraphSubNodeType.Text, content: "臣本布衣" },
          { type: ParagraphSubNodeType.Punctuation, content: "，" },
          { type: ParagraphSubNodeType.Text, content: "躬耕於南陽" },
          { type: ParagraphSubNodeType.Punctuation, content: "，" },
          { type: ParagraphSubNodeType.Text, content: "苟全性命於亂世" },
          { type: ParagraphSubNodeType.Punctuation, content: "，" },
          { type: ParagraphSubNodeType.Text, content: "不求聞達於諸侯" },
          { type: ParagraphSubNodeType.Punctuation, content: "。" },
          { type: ParagraphSubNodeType.Text, content: "先帝不以臣卑鄙" },
          { type: ParagraphSubNodeType.Punctuation, content: "，" },
          { type: ParagraphSubNodeType.Text, content: "猥自枉屈" },
          { type: ParagraphSubNodeType.Punctuation, content: "，" },
          { type: ParagraphSubNodeType.Text, content: "三顧臣於草廬之中" },
          { type: ParagraphSubNodeType.Punctuation, content: "，" },
          { type: ParagraphSubNodeType.Text, content: "諮臣以當世之事；由是感激" },
          { type: ParagraphSubNodeType.Punctuation, content: "，" },
          { type: ParagraphSubNodeType.Text, content: "遂許先帝以驅馳" },
          { type: ParagraphSubNodeType.Punctuation, content: "。" },
          { type: ParagraphSubNodeType.Text, content: "後值傾覆" },
          { type: ParagraphSubNodeType.Punctuation, content: "，" },
          { type: ParagraphSubNodeType.Text, content: "受任於敗軍之際" },
          { type: ParagraphSubNodeType.Punctuation, content: "，" },
          { type: ParagraphSubNodeType.Text, content: "奉命於危難之間" },
          { type: ParagraphSubNodeType.Punctuation, content: "，" },
          { type: ParagraphSubNodeType.Text, content: "爾來二十有一年矣" },
          { type: ParagraphSubNodeType.Punctuation, content: "。" },
          { type: ParagraphSubNodeType.Text, content: "先帝知臣謹慎" },
          { type: ParagraphSubNodeType.Punctuation, content: "，" },
          { type: ParagraphSubNodeType.Text, content: "故臨崩寄臣以大事也" },
          { type: ParagraphSubNodeType.Punctuation, content: "。" },
          { type: ParagraphSubNodeType.Text, content: "受命以來" },
          { type: ParagraphSubNodeType.Punctuation, content: "，" },
          { type: ParagraphSubNodeType.Text, content: "夙夜憂歎" },
          { type: ParagraphSubNodeType.Punctuation, content: "，" },
          { type: ParagraphSubNodeType.Text, content: "恐託付不效" },
          { type: ParagraphSubNodeType.Punctuation, content: "，" },
          { type: ParagraphSubNodeType.Text, content: "以傷先帝之明" },
          { type: ParagraphSubNodeType.Punctuation, content: "。" },
          { type: ParagraphSubNodeType.Text, content: "故五月渡瀘" },
          { type: ParagraphSubNodeType.Punctuation, content: "，" },
          { type: ParagraphSubNodeType.Text, content: "深入不毛" },
          { type: ParagraphSubNodeType.Punctuation, content: "。" },
          { type: ParagraphSubNodeType.Text, content: "今南方已定" },
          { type: ParagraphSubNodeType.Punctuation, content: "，" },
          { type: ParagraphSubNodeType.Text, content: "兵甲已足" },
          { type: ParagraphSubNodeType.Punctuation, content: "，" },
          { type: ParagraphSubNodeType.Text, content: "當獎率三軍" },
          { type: ParagraphSubNodeType.Punctuation, content: "，" },
          { type: ParagraphSubNodeType.Text, content: "北定中原" },
          { type: ParagraphSubNodeType.Punctuation, content: "，" },
          { type: ParagraphSubNodeType.Text, content: "庶竭駑鈍" },
          { type: ParagraphSubNodeType.Punctuation, content: "，" },
          { type: ParagraphSubNodeType.Text, content: "攘除姦凶" },
          { type: ParagraphSubNodeType.Punctuation, content: "，" },
          { type: ParagraphSubNodeType.Text, content: "興復漢室" },
          { type: ParagraphSubNodeType.Punctuation, content: "，" },
          { type: ParagraphSubNodeType.Text, content: "還於舊都" },
          { type: ParagraphSubNodeType.Punctuation, content: "。" },
          { type: ParagraphSubNodeType.Text, content: "此臣所以報先帝而忠陛下之職分也" },
          { type: ParagraphSubNodeType.Punctuation, content: "。" },
          { type: ParagraphSubNodeType.Text, content: "至於斟酌損益" },
          { type: ParagraphSubNodeType.Punctuation, content: "，" },
          { type: ParagraphSubNodeType.Text, content: "進盡忠言" },
          { type: ParagraphSubNodeType.Punctuation, content: "，" },
          { type: ParagraphSubNodeType.Text, content: "則攸之、禕、允之任也" },
          { type: ParagraphSubNodeType.Punctuation, content: "。" },
        ],
      },
      {
        textSegments: [
          "願陛下託臣以討賊興復之效；不效",
          "則治臣之罪",
          "以告先帝之靈",
          "若無興德之言",
          "則責攸之、禕、允等之慢",
          "以彰其咎",
          "陛下亦宜自謀",
          "以諮諏善道",
          "察納雅言",
          "深追先帝遺詔",
          "臣不勝受恩感激",
          "今當遠離",
          "臨表涕零",
          "不知所言",
        ],
        subNodes: [
          { type: ParagraphSubNodeType.Text, content: "願陛下託臣以討賊興復之效；不效" },
          { type: ParagraphSubNodeType.Punctuation, content: "，" },
          { type: ParagraphSubNodeType.Text, content: "則治臣之罪" },
          { type: ParagraphSubNodeType.Punctuation, content: "，" },
          { type: ParagraphSubNodeType.Text, content: "以告先帝之靈" },
          { type: ParagraphSubNodeType.Punctuation, content: "。" },
          { type: ParagraphSubNodeType.Text, content: "若無興德之言" },
          { type: ParagraphSubNodeType.Punctuation, content: "，" },
          { type: ParagraphSubNodeType.Text, content: "則責攸之、禕、允等之慢" },
          { type: ParagraphSubNodeType.Punctuation, content: "，" },
          { type: ParagraphSubNodeType.Text, content: "以彰其咎" },
          { type: ParagraphSubNodeType.Punctuation, content: "。" },
          { type: ParagraphSubNodeType.Text, content: "陛下亦宜自謀" },
          { type: ParagraphSubNodeType.Punctuation, content: "，" },
          { type: ParagraphSubNodeType.Text, content: "以諮諏善道" },
          { type: ParagraphSubNodeType.Punctuation, content: "，" },
          { type: ParagraphSubNodeType.Text, content: "察納雅言" },
          { type: ParagraphSubNodeType.Punctuation, content: "，" },
          { type: ParagraphSubNodeType.Text, content: "深追先帝遺詔" },
          { type: ParagraphSubNodeType.Punctuation, content: "。" },
          { type: ParagraphSubNodeType.Text, content: "臣不勝受恩感激" },
          { type: ParagraphSubNodeType.Punctuation, content: "。" },
          { type: ParagraphSubNodeType.Text, content: "今當遠離" },
          { type: ParagraphSubNodeType.Punctuation, content: "，" },
          { type: ParagraphSubNodeType.Text, content: "臨表涕零" },
          { type: ParagraphSubNodeType.Punctuation, content: "，" },
          { type: ParagraphSubNodeType.Text, content: "不知所言" },
          { type: ParagraphSubNodeType.Punctuation, content: "！" },
        ],
      },
    ],
    allTextSegments: [
      "先帝創業未半",
      "而中道崩殂",
      "今天下三分",
      "益州疲弊",
      "此誠危急存亡之秋也",
      "然侍衞之臣",
      "不懈於內；忠志之士",
      "忘身於外者",
      "蓋追先帝之殊遇",
      "欲報之於陛下也",
      "誠宜開張聖聽",
      "以光先帝遺德",
      "恢弘志士之氣；不宜妄自菲薄",
      "引喻失義",
      "以塞忠諫之路也",
      "宮中、府中",
      "俱為一體",
      "陟罰臧否",
      "不宜異同",
      "若有作姦、犯科",
      "及為忠善者",
      "宜付有司",
      "論其刑賞",
      "以昭陛下平明之治",
      "不宜偏私",
      "使內外異法也",
      "侍中、侍郎郭攸之、費禕、董允等",
      "此皆良實",
      "志慮忠純",
      "是以先帝簡拔以遺陛下",
      "愚以為宮中之事",
      "事無大小",
      "悉以咨之",
      "然後施行",
      "必能裨補闕漏",
      "有所廣益",
      "將軍向寵",
      "性行淑均",
      "曉暢軍事",
      "試用於昔日",
      "先帝稱之曰「能」",
      "是以眾議舉寵為督",
      "愚以為營中之事",
      "悉以咨之",
      "必能使行陣和睦",
      "優劣得所",
      "親賢臣",
      "遠小人",
      "此先漢所以興隆也；親小人",
      "遠賢臣",
      "此後漢所以傾頹也",
      "先帝在時",
      "每與臣論此事",
      "未嘗不歎息痛恨於桓、靈也",
      "侍中、尚書、長史、參軍",
      "此悉貞良死節之臣",
      "願陛下親之信之",
      "則漢室之隆",
      "可計日而待也",
      "臣本布衣",
      "躬耕於南陽",
      "苟全性命於亂世",
      "不求聞達於諸侯",
      "先帝不以臣卑鄙",
      "猥自枉屈",
      "三顧臣於草廬之中",
      "諮臣以當世之事；由是感激",
      "遂許先帝以驅馳",
      "後值傾覆",
      "受任於敗軍之際",
      "奉命於危難之間",
      "爾來二十有一年矣",
      "先帝知臣謹慎",
      "故臨崩寄臣以大事也",
      "受命以來",
      "夙夜憂歎",
      "恐託付不效",
      "以傷先帝之明",
      "故五月渡瀘",
      "深入不毛",
      "今南方已定",
      "兵甲已足",
      "當獎率三軍",
      "北定中原",
      "庶竭駑鈍",
      "攘除姦凶",
      "興復漢室",
      "還於舊都",
      "此臣所以報先帝而忠陛下之職分也",
      "至於斟酌損益",
      "進盡忠言",
      "則攸之、禕、允之任也",
      "願陛下託臣以討賊興復之效；不效",
      "則治臣之罪",
      "以告先帝之靈",
      "若無興德之言",
      "則責攸之、禕、允等之慢",
      "以彰其咎",
      "陛下亦宜自謀",
      "以諮諏善道",
      "察納雅言",
      "深追先帝遺詔",
      "臣不勝受恩感激",
      "今當遠離",
      "臨表涕零",
      "不知所言",
    ],
  };
  const result = generateQuestionFromOriginalEssay(originalEssay);
});
